//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Mail
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdProgrammer { get; set; }
        public Nullable<int> IdRole { get; set; }
    
        public virtual Programmer Programmer { get; set; }
        public virtual Role Role { get; set; }
    }
}
